- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/predictions/"
    dataloader_config:
      num_workers: 8
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/evaluations/"
  model:
    name: "lstm_1x128__0303335_no_past"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/predictions/"
    dataloader_config:
      num_workers: 8
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/evaluations/"
  model:
    name: "lstm_3x128__0303335_no_past"
