test:
  normalize: True
  data_config:
    noise_config:
      exclude_road: False
      hide_target_past: False
      noisy_heading: False
      training: False
    dataset_config:
      data_path: "/home/manolotis/sandbox/scenario_based_evaluation/lstmEncoderDecoder/data/prerendered/testing/"
      mask_history: False
      n_shards: 1
      input_data: [ "xy", "yaw", "v_xy", "width", "length", "valid" ]
    dataloader_config:
      batch_size: 8
      shuffle: False
      num_workers: 8
  output_config:
    visualize: False
    out_path: "/home/manolotis/sandbox/scenario_based_evaluation/lstmEncoderDecoder/predictions/"
    viz_path: "/home/manolotis/sandbox/scenario_based_evaluation/lstmEncoderDecoder/plots/predictions/"


model:
  name: "lstm_1x512__0303335"
  path: "/home/manolotis/sandbox/scenario_based_evaluation/lstmEncoderDecoder/trained_models/"
  n_trajectories: 1
  prediction_steps: 80
  encoder:
    num_layers: 1
    hidden_size: 512
    input_size: 14

  decoder:
    num_layers: 1
    hidden_size: 512
    prediction_features: 2

