data_path: "/home/manolotis/sandbox/waymoMotion/data/reduced/tf_example/training/"
output_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/data/prerendered/training"
n_jobs: 16
n_shards: 1
shard_id: 0
multiprocessing: True
renderers:
  - renderer_name: LSTMAutoencoderRenderer
    renderer_config:
      normalize: False
      agent_filtering:
        policy: "interesting"
      noisy_heading : True


